esphome:
  name: m5plc
  friendly_name: m5plc
  build_path: /config/esphome/m5plcbuild
  on_boot:
    priority: 1000  #aw9523 and pi4ioe5v6408 need GPIO3 high to work.
    then:
      - lambda: |-
                gpio_set_direction(GPIO_NUM_3, GPIO_MODE_OUTPUT);
                gpio_set_level(GPIO_NUM_3, 1);

esp32:
  board: esp32-s3-devkitc-1
  framework:
    type: esp-idf

logger:
  level: DEBUG
  baud_rate: 0
  logs:
    api.service: WARN
    wifi: WARN
    esp-idf: NONE
api:
  encryption:
    key: !secret api_key
  reboot_timeout: 6h
  actions:
    - action: rtttl_play
      variables:
        song_str: string
      then:
        - rtttl.play:
            rtttl: !lambda 'return song_str;'
ota:
  - platform: esphome
    #password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  reboot_timeout: 6h
  #power_save_mode: LIGHT

external_components:
  - source: github://patrick3399/esphome_components
  # - source: github://n-serrette/esphome_sd_card   #If need SD Card Support

uart:
  - id: uart_485 #StamPLC RS485
    tx_pin: GPIO0
    rx_pin: GPIO39
    # RS485_DIR GPIO46
    baud_rate: 9600
  - id: uart_can #StamPLC CAN
    tx_pin: GPIO42
    rx_pin: GPIO43
    baud_rate: 9600

spi:
  - id: spi_bus0
    clk_pin: GPIO7
    mosi_pin: GPIO8
    interface: hardware
i2c:
  id: main_i2c
  sda: GPIO13
  scl: GPIO15
  scan: False
  frequency: 200kHz

aw9523:
  id: aw9523_hub
  address: 0x59
  update_interval: 0ms
  i2c_id: main_i2c

pi4ioe5v6408:
  id: pi4ioe5v6408_hub
  address: 0x43
  update_interval: 0ms
  i2c_id: main_i2c

# sd_mmc_card:  #If need SD Card Support
#   id: micro_sd
#   mode_1bit: true
#   clk_pin: GPIO7
#   cmd_pin: GPIO8
#   data0_pin: GPIO9
#   data3_pin: GPIO10

# sd_file_server:  #If need SD Card Support
#   id: file_server
#   url_prefix: file
#   root_path: "/"
#   enable_deletion: true
#   enable_download: true
#   enable_upload: true

binary_sensor:
  - platform: gpio
    name: "IN1"
    pin:
      aw9523: aw9523_hub
      number: 4
      mode:
        input: true
      inverted: false
  - platform: gpio
    name: "IN2"
    pin:
      aw9523: aw9523_hub
      number: 5
      mode:
        input: true
      inverted: false
  - platform: gpio
    name: "IN3"
    pin:
      aw9523: aw9523_hub
      number: 6
      mode:
        input: true
      inverted: false
  - platform: gpio
    name: "IN4"
    pin:
      aw9523: aw9523_hub
      number: 7
      mode:
        input: true
      inverted: false
  - platform: gpio
    name: "IN5"
    pin:
      aw9523: aw9523_hub
      number: 12
      mode:
        input: true
      inverted: false
  - platform: gpio
    name: "IN6"
    pin:
      aw9523: aw9523_hub
      number: 13
      mode:
        input: true
      inverted: false
  - platform: gpio
    name: "IN7"
    pin:
      aw9523: aw9523_hub
      number: 14
      mode:
        input: true
      inverted: false
  - platform: gpio
    name: "IN8"
    pin:
      aw9523: aw9523_hub
      number: 15
      mode:
        input: true
      inverted: false
  - platform: gpio
    name: "Button C"
    pin:
      pi4ioe5v6408: pi4ioe5v6408_hub
      number: 0
      mode:
        input: true
      inverted: true
  - platform: gpio
    name: "Button B"
    pin:
      pi4ioe5v6408: pi4ioe5v6408_hub
      number: 1
      mode:
        input: true
      inverted: true
  - platform: gpio
    name: "Button A"
    pin:
      pi4ioe5v6408: pi4ioe5v6408_hub
      number: 2
      mode:
        input: true
      inverted: true


switch:
  - platform: gpio
    name: "Relay 1"
    pin:
      aw9523: aw9523_hub
      number: 0
      mode:
        output: true
      inverted: false
  - platform: gpio
    name: "Relay 2"
    pin:
      aw9523: aw9523_hub
      number: 1
      mode:
        output: true
      inverted: false
  - platform: gpio
    name: "Relay 3"
    pin:
      aw9523: aw9523_hub
      number: 2
      mode:
        output: true
      inverted: false
  - platform: gpio
    name: "Relay 4"
    pin:
      aw9523: aw9523_hub
      number: 3
      mode:
        output: true
      inverted: false
  - platform: gpio
    name: "LED Blue"
    pin:
      pi4ioe5v6408: pi4ioe5v6408_hub
      number: 4
      mode:
        output: true
      inverted: true
  - platform: gpio
    name: "LED Green"
    pin:
      pi4ioe5v6408: pi4ioe5v6408_hub
      number: 5
      mode:
        output: true
      inverted: true
  - platform: gpio
    name: "LED Red"
    pin:
      pi4ioe5v6408: pi4ioe5v6408_hub
      number: 6
      mode:
        output: true
      inverted: true
  - platform: gpio
    name: "Screen Backlight"
    restore_mode: ALWAYS_ON
    pin:
      pi4ioe5v6408: pi4ioe5v6408_hub
      number: 7
      mode:
        output: true
      inverted: True

sensor:
  - platform: lm75
    id: temperature
    name: "Board Temp"
    update_interval: 60s
    address: 0x48
    i2c_id: main_i2c
  - platform: internal_temperature
    name: "Chip Temp"
  - platform: ina226
    address: 0x40
    i2c_id: main_i2c
    shunt_resistance: 0.1 ohm
    max_current: 3.2A
    adc_time: 140us
    adc_averaging: 128
    update_interval: 60s
    current:
      name: "INA226 Current"
    power:
      name: "INA226 Power"
    bus_voltage:
      name: "INA226 Bus Voltage"
    shunt_voltage:
      name: "INA226 Shunt Voltage"

  # - platform: sd_mmc_card  #If need SD Card Support
  #   type: used_space
  #   name: "SD card used space"
  # - platform: sd_mmc_card
  #   type: total_space
  #   name: "SD card total space"


# text_sensor:
  # - platform: sd_mmc_card  #If need SD Card Support
  #   sd_card_type:
  #     name: "SD card type"

time:
  - platform: homeassistant
    id: homeassistant_time
    update_interval: 1h
    on_time_sync:
      then:
        rx8130ce.write_time:
          id: rx8130ce_rtc
  - platform: rx8130ce
    id: rx8130ce_rtc
    address: 0x32
    update_interval: never

display:
  - platform: st7789v
    model: TTGO_TDISPLAY_135X240
    offset_height: 52
    offset_width: 40
    rotation: 90
    cs_pin: GPIO12
    dc_pin: GPIO6
    reset_pin: GPIO36  #Set Reset Pin at Unuseable Pin.
    data_rate: 40MHz
    update_interval: 30s
    lambda: |-

      it.line(3, 0, 239, 0);
      it.line(239, 0, 239, 134);
      it.line(3, 0, 3, 134);
      it.line(3, 134, 239, 134);
      it.print(121, 66, id(Roboto24), TextAlign::CENTER, id(DisplayText).state.c_str());

font:
  - file: "gfonts://Roboto"
    id: Roboto24
    size: 24
text:
  - platform: template
    name: "Display TEXT"
    id: DisplayText
    optimistic: true
    min_length: 0
    max_length: 26
    initial_value: 'Default TEXT'
    mode: text

output:
  - platform: ledc
    id: rtttl_pin
    pin: 44
rtttl:
  output: rtttl_pin
  id: rtttl_buzz
  gain: 60%
