wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  reboot_timeout: 6h

sensor:
  - platform: wifi_signal
    id: wifi_signal_sensor
    name: "WiFi RSSI"
    entity_category: diagnostic
    update_interval: 30s
